### ISSUE TITLE
false positive camo.githubusercontent.com

### ISSUE THREAD

**Issue by Uranite** [j-moriarti/pDNSf-Hosts-collection#10]
go to https://github.com/AdguardTeam/AdguardFilters
and there should be an image like this
![Screenshot_20210710-060319~2](https://user-images.githubusercontent.com/62639703/125143359-abb93700-e144-11eb-84ca-55e8fdc4fa2d.png)

**Comment by j-moriarti** [comment]
Thanks for your reporting and the example url! :+1: I checked and found that it was blocked by this source: [gameindustry_main_hosts](https://raw.githubusercontent.com/KodoPengin/GameIndustry-hosts-Template/master/Main-Template/hosts). It will be fixed in next update! Also I have reported it to that source maintainer.
