### ISSUE TITLE
Hosts file clean up

### ISSUE THREAD

**Issue by keweon** [j-moriarti/pDNSf-Hosts-collection#2]
Hi there!

I was looking at your hosts file and the link below contains a list with all non valid or non existing entries.
Hope you enjoy this.

If you want to block domains as like as this one:
`автодиагностика.рф`
you need to convert this to punycode or it will be not blocked. (punycoder.com)
`автодиагностика.рф = xn--80aaagge2acs2agf3bgi.xn--p1ai`

Here is the list of removeable entries within your hosts file. All IP addresses are excluded because they are ignored anyway within a hosts file:

https://pastebin.com/raw/VHtQvMm7

Greetings!

**Comment by j-moriarti** [comment]
Hi!
thanks for your suggestions! Actually I've found the only source that has those type of domains, and since it has not been updated in a while, I was going to replace it, so it would be get fixed. but as you said, I may add a code to convert them to punycode. BTW, thanks for the lists! I will take a look at them to recognize issues and improve my code :slightly_smiling_face: 

and about IP addresses! I intentionally not removed them, since pDNSf app supports blocking IP addresses. But I will remove (separate) them to generalize the hosts file. I may create extra hosts with 0.0.0.0 and 127.0.0.1 format, too!

**Comment by j-moriarti** [comment]
I have enhanced my code to support and fix the issues you've mentioned. you may re-check the hosts to see if everything is ok :) , thanks!
