### ISSUE TITLE
re: 1Hosts (Pro)

### ISSUE THREAD

**Issue by badmojr** [j-moriarti/pDNSf-Hosts-collection#5]
Hello!
The current setup includes http://o0.pages.dev/Pro/xtra/domains.txt, which is a supplementary/addon list for 1Hosts (Pro).
Why is the addon the only list being included?

Cheers!

**Comment by j-moriarti** [comment]
Hi!
I (most of the times) try to compare my new sources with other big hosts (like energized or others) to avoid duplication. Since 1Hosts pro is already included in energized ultimate (which is already one of my sources), it was removed from list (https://github.com/j-moriarti/pDNSf-Hosts-collection/commit/b7464f4addecf30257d1014ef7799f36ed0b4051).
But I just checked and energized uses old address of 1Hosts pro, so I'm planning to manually add all sub-sources to the list.

BTW, Thank you for your attention. I appreciate your work :clap:

**Comment by badmojr** [comment]
Cool!
Energized Ultimate also includes only 1Hosts (mini) currently.
Ador seems to have made some changes recentl;y.
https://github.com/EnergizedProtection/block/blob/master/ultimate/build.sh#L115
https://github.com/EnergizedProtection/block/blob/master/assets/sources/sources.json#L2

Keep up the good work!!
